language: node_js
node_js:
  - 0.10
notifications:
  slack:
    secure: CI3y9riikfzzBEoHWM0482Aj0oFcENm5Hi6z5Lo1pPgwCkY6YcxGaYM54EDCCh8e24IAecVagBE2KEusrcU0F+/zoVJE3QTxr5PRj1AIDvbAW1tMXbz0ckqHnUAW48ox55NNSeaOXxmJ2LNX6t2q5qorf0LnuCRc2OhSOR6PUOM=
