name: Testing

on: push

jobs:
  test:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [8.15, 10.x, 12.x, 14.x]
      
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run tests
      run: npm run test:coverage:lcov
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
